name: craigtregear
favicon: null
layout_spectrum: 0.5938332735095173
typography_spectrum: 0.16332467319443822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4172697477042675
  lightness: 0.7626088527031243
  saturation: 0.17483945027925074
  rhythmicContrast: 0.9763406859710813
purpose: []
