name: craigtregear
favicon: null
layout_spectrum: 0.94181
typography_spectrum: 0.28132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0e0a09'
    - '#4a4542'
    - '#fe8e0e'
    - '#fb291c'
  brandStrength: 0.6875
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
